### PR TITLE
Onboarding

### PR DESCRIPTION
**Pull request by dkoloditch**
On-boarding / Getting Started documentation.

### CODE REVIEW

**Comment by dviramontes** [comment]
Looks great thanks @dkoloditch !
Merging.

**Comment by wdoug** [comment]
Question @dkoloditch @dviramontes? I thought I saw a mention of this being added as a Readme to the org repo. Should we move it from here (the site repo) over there and have a Readme specific to the website here?

**Comment by dviramontes** [comment]
yeah, i was just going GET request it from the code-for-denver-site but it does make more since to move it to the org repo

**Comment by dkoloditch** [comment]
Sorry about that. I thought the org repo you were referring to was the repo for the site (codefordenver.ORG).  I'll go ahead and move it over. Link to the org repo?

**Comment by dviramontes** [comment]
https://github.com/codefordenver/org

**Comment by wdoug** [comment]
Oh haha

**Pull request merged**
