### PR TITLE
david/get-involved

### PR DESCRIPTION
**Pull request by dviramontes**
Adds get-involved section animation.
Kudos to @wdoug for helping debug :+1:

### CODE REVIEW

**Comment by wdoug** [comment]
Can we just keep this simple at the moment and not use 6to5? Also, do we really want to have a build step at this point?

I will review this again tonight when I get some more time.

**Comment by dviramontes** [comment]
sure but 6to5 is only used locally
to transpile the code 
i.e. es6-> es5

the build step is only for main.js
everything else is a normal <script> tag
as it was before

system.js also loads anything
you ask it to. I thought it would be a good idea,
in order to play nice with whatever
people want to bring in
(amd vs browserify vs es6-module)

jspm allows us to bring in node-modules
and bower_components with one interface

yeah lets talk about, it does feel a bit  
[complecting](http://www.thefreedictionary.com/complecting)

im open to just doing it in simpler.

**Comment by wdoug** [comment]
... but it will still override any changes people make in main.js manually

**Comment by dviramontes** [comment]
true, however allow me to refactor to show you what i mean

**Comment by wdoug** [comment]
Sounds good :)

**Comment by dviramontes** [comment]
That last commit is more like it. Where the code is a module invoked by main.js

**Comment by dviramontes** [comment]
@wdoug should we merge this in ?
maybe we can make the changes you talked about this weekend

**Comment by wdoug** [comment]
Well there are merge conflicts currently, so we would have to deal with those first, but I'd say let's wait and work on it on Saturday.

**Comment by dviramontes** [comment]
ok

**Comment by dviramontes** [comment]
look at #36

**Pull request closed without merging**
